  name: GitHub Pages
  on: 
    push:
      branches: [ "main" ]
  jobs:
  # This workflow contains a single job called "build"
    build:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version:  21
          cache: 'npm'
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm ci
      - run: pnpm run deploy
